
# Environment
ENV_WIDTH_CELLS = 20
ENV_HEIGHT_CELLS = 10

# Cell
CELL_WIDTH = 48
CELL_HEIGHT = 48

BUTTON_WIDTH = 48

# WINDOW
WIN_WIDTH = ENV_WIDTH_CELLS * CELL_WIDTH + BUTTON_WIDTH
WIN_HEIGHT = ENV_HEIGHT_CELLS * CELL_HEIGHT
DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
BACKGROUND_COLOR = "#FFFFFF"


# Player
HP = 100
PLAYER_WIDTH = 1 * CELL_WIDTH
PLAYER_HEIGHT = 1 * CELL_HEIGHT
PLAYER_COLOR = COLOR = "#888888"


